mystore/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('shop.urls')),
]

#Ajout d'une configuration pour correctement afficher élément dans panneau admin lorsque le site est encore en mode DEBUG : 
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

mystore/shop/urls.py
from django.urls import path
from shop.views import shop_view , cart_view, compare_view, wishlist_view, checkout_view

app_name="shop" #nom de l'app

urlpatterns = [
    #Shop
    path('', shop_view.index, name='home'),
    path('page/<str:slug>', shop_view.display_page, name='page'),
    path('product/<str:slug>', shop_view.display_product, name='single_product'),
    path('shop', shop_view.shop, name='shop_list'),

    #Cart (panier)
    path('cart', cart_view.index, name='cart'),
    path('cart/add/<int:product_id>', cart_view.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/<int:quantity>', cart_view.remove_from_cart, name='remove_from_cart'),

    #Comparaison
    path('compare', compare_view.index, name='compare'),
    path('compare/add/<int:product_id>', compare_view.add_to_compare, name='add_to_compare'),
    path('compare/remove/<int:product_id>', compare_view.remove_from_compare, name='remove_from_compare'),

    #Liste des souhaits
    path('wishlist', wishlist_view.index, name='wishlist'),
    path('wishlist/add/<int:product_id>', wishlist_view.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:product_id>', wishlist_view.remove_from_wishlist, name='remove_from_wishlist'),

    #Checkout
    path('checkout', checkout_view.index, name='checkout'),
    path('checkout/add_address', checkout_view.add_address, name='add_address'),

]

mystore/shop/models/Carrier.py
from django.db import models
from django.utils.text import slugify

class Carrier(models.Model):
    name = models.CharField(max_length=60, blank=False, null=False)
    description = models.CharField(max_length=120,blank=False, null=False)
    details = models.TextField()
    price = models.FloatField()
    image = models.ImageField(upload_to="carrier_images", blank=False, null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta : #gestion du nom afficher dans le pannel admin du site 
        verbose_name = 'Transporteur'
        verbose_name_plural = 'Transporteurs'


    def __str__(self): #affichage sous forme de chaine de caractère
        return f"{self.name} ( {self.price} €)"

mystore/shop/models/Category.py
from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=60, blank=False, null=False)
    description = models.CharField(max_length=120,blank=False, null=False)
    slug = models.SlugField(max_length=255,blank=False, null=False)
    image = models.ImageField(upload_to="category_images", blank=False, null=False)
    is_mega = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta : #gestion du nom afficher dans le pannel admin du site (soit category ou categories)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs) : #création du champ slug lors de la création dans le panel admin
        if not self.slug :
            self.slug = slugify(self.name)
        super().save( *args, **kwargs)

    def __str__(self): #affichage sous forme de chaine de caractère
        return self.name

mystore/shop/models/Collection.py
from django.db import models

class Collection(models.Model):
    title = models.CharField(max_length=60, blank=False, null=False)
    description = models.CharField(max_length=120,blank=False, null=False)
    button_text = models.CharField(max_length=60,blank=False, null=False)
    button_link = models.CharField(max_length=255,blank=False, null=False)
    image = models.ImageField(upload_to="sliders", blank=False, null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): #affichage sous forme de chaine de caractère
        return self.title
    

mystore/shop/models/Image.py
from django.db import models
from shop.models.Product import Product

class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to="product_images/",blank=False, null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

mystore/shop/models/Navcollection.py
from django.db import models

class Navcollection(models.Model):
    title = models.CharField(max_length=60, blank=False, null=False)
    description = models.CharField(max_length=120,blank=False, null=False)
    button_text = models.CharField(max_length=60,blank=False, null=False)
    button_link = models.CharField(max_length=255,blank=False, null=False)
    image = models.ImageField(upload_to="nav_collections", blank=False, null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): #affichage sous forme de chaine de caractère
        return self.title

mystore/shop/models/Product.py
from django.db import models
from shop.models.Category import Category
from django.utils.text import slugify


class Product(models.Model):
    name = models.CharField(max_length=60,blank=False, null=False)
    slug = models.SlugField(max_length=255,blank=False, null=False)
    description = models.CharField(max_length=120,blank=False, null=False)
    more_description = models.TextField(blank=True, null=True)
    additional_infos = models.TextField(blank=True, null=True)
    stock = models.IntegerField(blank=False, null=False)
    solde_price = models.FloatField(blank=False, null=False)
    regular_price = models.FloatField(blank=False, null=False)
    brand = models.CharField(max_length=60,blank=True, null=True)
    is_available = models.BooleanField(blank=False, null=False)
    is_best_seller = models.BooleanField(blank=False, null=False)
    is_new_arrival = models.BooleanField(blank=False, null=False)
    is_featured = models.BooleanField(blank=False, null=False)
    is_special_offer = models.BooleanField(blank=False, null=False)
    categories = models.ManyToManyField(Category)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs) : #création du champ slug lors de la création dans le panel admin
        if not self.slug :
            self.slug = slugify(self.name)
        super().save( *args, **kwargs)

mystore/shop/models/Social.py
from django.db import models

class Social(models.Model):
    name = models.CharField(max_length=60,blank=False, null=False)
    icon = models.CharField(max_length=120,blank=False, null=False)
    link = models.CharField(max_length=255,blank=False, null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

mystore/shop/forms/CheckoutAddressForm.py
from django import forms
from dashboard.models.Address import Address

class CheckoutAddressForm(forms.ModelForm):
    #Les différents choix de type d'adresse avec le champ de formulaire auquel on attribue un attribut classe au widget 
    ADDRESS_TYPE_CHOICES = [('billing', 'Billing'), ('shipping', 'Shipping')] #Précision s'il s'agit de l'adresse de livraison ou de facturation 

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class' : 'form-control'}))
    address_type = forms.ChoiceField(
        choices=ADDRESS_TYPE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control custom-text-input'})
    )

    class Meta:
        model = Address
        fields = ('email','name', 'full_name', 'street', 'code_postal', 'city', 'country', 'more_details', 'address_type')

        #Personnalisation des champs du formulaire via widget (attrs permet l'attribution d'attribut aux champs) : 
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control custom-text-input'}),
            'full_name' : forms.TextInput(attrs={'class': 'form-control custom-text-input'}),
            'street' : forms.TextInput(attrs={'class': 'form-control custom-text-input'}),
            'code_postal' : forms.TextInput(attrs={'class': 'form-control custom-text-input'}),
            'city' : forms.TextInput(attrs={'class': 'form-control custom-text-input'}),
            'country' : forms.TextInput(attrs={'class': 'form-control custom-text-input'}),
            'more_details' : forms.Textarea(attrs={'class': 'form-control custom-textarea'}),

        }

mystore/shop/views/cart_view.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models.Product import Product
from shop.services.cart_service import CartService
from shop.models.Carrier import Carrier


def index(request):

    #Récupération du carrier id via la barre d'adresse
    carrier_id = request.GET.get('carrier_id')
    if carrier_id and carrier_id != '':
        carrier = Carrier.objects.filter(id=carrier_id).first()
        if carrier :
            request.session['carrier'] = {
                'id' : carrier.id,
                'name' : carrier.name,
                'price' : carrier.price,
            }

    cart = CartService.get_cart_details(request)

     #vérifier si il y a quelque chose dans le panier sinon rediriger vers page home
    if not len(cart['items']):
        return redirect('shop:home')
    
    #Récupération de transporteurs 
    carriers = Carrier.objects.all()

    return render(request, 'shop/cart.html', {'cart': cart, 'carriers':carriers})


def add_to_cart(request, product_id):
    CartService.add_to_cart(request, product_id, 1)
    return redirect('shop:cart')


def remove_from_cart(request, product_id, quantity=1):
    CartService.remove_from_cart(request, product_id, quantity)
    return redirect('shop:cart')

mystore/shop/views/checkout_view.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.services.cart_service import CartService
from shop.models.Carrier import Carrier
from shop.forms.CheckoutAddressForm import CheckoutAddressForm
from django.contrib import messages


def index(request):
    #Récupération du carrier id via la barre d'adresse
    carrier_id = request.GET.get('carrier_id')
    if carrier_id and carrier_id != '':
        carrier = Carrier.objects.filter(id=carrier_id).first()
        if carrier :
            request.session['carrier'] = {
                'id' : carrier.id,
                'name' : carrier.name,
                'price' : carrier.price,
            }

    cart = CartService.get_cart_details(request)
    carriers = Carrier.objects.all()
    address_form = CheckoutAddressForm()
    return render(request, 'shop/checkout.html', {
        'cart' : cart, 
        'carriers' : carriers,
        'address_form' : address_form,
        })

def add_address(request):
    user = request.user
    
    #Vérification de la méthode
    if request.method == 'POST' :
        #Récupération du formulaire
        address_form = CheckoutAddressForm(request.POST)
        #Vérification de la validité
        if address_form.is_valid():
            address = address_form.save(commit=False) #sauvegarde sans envois en base de donné
            address.author = user #Association de l'user à author
            address.save()
            messages.success(request, 'Adresse correctement ajoutée.')


    return redirect('shop:checkout')

mystore/shop/views/compare_view.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.services.compare_service import CompareService


def index(request):
    compares = CompareService.get_compared_products_details(request)
    return render(request, 'shop/compare.html', {'compares' : compares})

def add_to_compare(request, product_id):
    CompareService.add_product_to_compare(request, product_id)
    return redirect('shop:compare')

def remove_from_compare(request, product_id):
    CompareService.remove_product_from_compare(request, product_id)
    return redirect('shop:compare')

mystore/shop/views/shop_view.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from shop.models.Slider import Slider
from shop.models.Collection import Collection
from shop.models.Product import Product
from shop.models.Page import Page
from shop.models.Category import Category


def index(request):
    sliders = Slider.objects.all()
    collections = Collection.objects.all()

    best_sellers = Product.objects.filter(is_best_seller=True)
    new_arrivals = Product.objects.filter(is_new_arrival=True)
    featured = Product.objects.filter(is_featured=True)
    special_offers = Product.objects.filter(is_special_offer=True)
    

    return render(request, 'shop/index.html', {
        'sliders' : sliders,
        'collections' : collections,
        'new_arrivals' : new_arrivals,
        'best_sellers' : best_sellers,
        'featured' : featured,
        'special_offers' : special_offers,

        })

def display_page(request, slug):
    page = get_object_or_404(Page, slug=slug)

    return render(request, 'shop/page.html', {
        'page' : page,
        })


def display_product(request, slug):
    product = get_object_or_404(Product, slug=slug)
   
    return render(request, 'shop/single_product.html', {
        'product' : product,
        })

def shop(request):


    #Récupération de toutes les catégories :
    categories = Category.objects.all()

    # Récupéaration du paramètre de tri par prix depuis la session, valeur par défaut : asc
    sort_by_price = request.session.get('sort-price', 'asc')

    # Récupération du nombre d'éléments à afficher par page depuis la session, valeur par défaut : 6  
    showing = int(request.session.get('showing', 6)) 

    # Récupération de la catégorie, valeur par défaut : all
    category_id = request.GET.get('category_id', 'all')

    if category_id and category_id != 'all':
        category = get_object_or_404(Category, id=category_id) #récupération de la catégorie ou renvois page 404
        products = category.product_set.all()  #récupération des produits de la catégorie
    else :
        products = Product.objects.all()  #Récupération de tous les produits 



    # Mise à jour du nombre d'éléments à afficher par page si présent dans les paramètres de requête
    if 'showing' in request.GET and request.GET['showing'] != "" :
        showing = request.GET['showing']
        request.session['showing'] = showing

 
    if 'category_id' in request.GET and request.GET['category_id'] != "" :
        category_id = request.GET['category_id']


    # Mise à jour du paramètre de tri par prix si présent dans les paramètres de requête    
    if 'sort-price' in request.GET and request.GET['sort-price'] != "" :
        sort_by_price = request.GET['sort-price']
        request.session['sort-price'] = sort_by_price
   

    page = request.GET.get('page', 1) #récupération de la page via url, si rien préciser dans url page par défaut : page 1
    display = request.session.get('display', 'grid') #récupération du type de display lors de la session valeur par défaut : grid

    # Mise à jour du paramètre d'affichage si présent dans les paramètres de requête  
    if 'display' in request.GET : 
        display = request.GET['display']
        request.session['display'] = display 


    # Tri des produits en fonction du paramètre sort_by_price
    if sort_by_price == "asc" :
        products = products.order_by('solde_price')
    elif sort_by_price == "desc" :
        products = products.order_by('-solde_price')

    paginator = Paginator(products, showing) #pagination du nombre de produit par page, valeur par défaut = showing

    try :
        products_page = paginator.page(page)

    except PageNotAnInteger: #gestion des cas de chaine de caractère ne correspondant pas à la demande rentrer en url 
        products_page = paginator.page(1)

    except EmptyPage: #gestion des cas ou le nombre mis en url est supérieur au nombre de page
        products_page = paginator.page(paginator.num_pages)

    except:
        products_page = paginator.page(1)

   #envois des infos au template pour premettre leur utilisation :
    return render(request, 'shop/shop_list.html', {
        'products' : products_page,
        'categories' : categories,
        'display' : display,
        'sort_by_price' : sort_by_price,
        'default_category_id' : int(category_id) if category_id.isdigit() else category_id,

        })

mystore/shop/views/wishlist_view.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.services.wish_service import WishService


def index(request):
    wishlist = WishService.get_wished_products_details(request)
    if not len(wishlist):
        return redirect('shop:home')
    return render(request, 'shop/wishlist.html', {'wishlist' : wishlist})

def add_to_wishlist(request, product_id):
    WishService.add_product_to_wish(request, product_id)
    return redirect('shop:wishlist')

def remove_from_wishlist(request, product_id):
    WishService.remove_product_from_wish(request, product_id)
    return redirect('shop:wishlist')

mystore/templates/shop/compare.html
{% extends "base.html" %}
{% load price_filter %}
{% block content %}

{% include "partials/top_page.html" with name="Compare" %}

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="compare_box">
                    <div class="table-responsive">
                        <table class="table table-bordered text-center">
                        <tbody>
                            <tr class="pr_image">
                                <td class="row_title">Le Produit</td>
                                {% for product in compares %}
                                <td class="row_img">
                                    <img src="{{ product.images.first.image.url }}" alt="{{ product.name }}">
                                </td>
                                {% endfor %}
                            </tr>
                            <tr class="pr_title">
                                <td class="row_title">Nom du Produit</td>
                                {% for product in compares %}
                                <td class="product_name">
                                    <a href="{% url 'shop:single_product' product.slug %}">{{ product.name }}</a>
                                </td>
                                {% endfor %}
                            </tr>
                            <tr class="pr_price">
                                <td class="row_title">Prix</td>
                                {% for product in compares %}
                                <td class="product_price">
                                    <span class="price">{{ product.solde_price | format_price }}</span>
                                </td>
                                {% endfor %}
                            <tr class="pr_add_to_cart">
                                <td class="row_title">Ajouter au panier</td>
                                {% for product in compares %}
                                <td class="row_btn">
                                    <a href="{% url 'shop:add_to_cart' product.id %}" class="btn btn-fill-out">
                                        <i class="icon-basket-loaded"></i> Ajouter au panier
                                    </a>
                                </td>
                                {% endfor %}
                            </tr>
                            <tr class="description">
                                <td class="row_title">Description</td>
                                {% for product in compares %}
                                    <td class="row_text">
                                        <p>{{ product.description }}</p>
                                    </td>
                                {% endfor %}
                            </tr>

                            <tr class="pr_stock">
                                <td class="row_title">Disponibilité</td>
                                {% for product in compares %}
                                        {% if product.stock > 0 %}
                                        <td class="row_stock"><span class="in-stock">En Stock</span></td>
                                        {% else %}
                                        <td class="row_stock"><span class="out-stock">Non disponible</span></td>
                                        {% endif %}
                                {% endfor %}
                            </tr>
                           
                            <tr class="pr_remove">
                                <td class="row_title"></td>
                                {% for product in compares %}
                                <td class="row_remove">
                                    <a href="{% url 'shop:remove_from_compare' product.id %}"><span>Supprimer</span> <i class="fa fa-times"></i></a>
                                </td>
                                {% endfor %}
                            </tr>
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mystore/templates/shop/index.html
{%extends "base.html" %}  

{%block content %}
   

{% include "partials/slider.html" with sliders=sliders %} <!-- Ligne servant à inclure les sliders sur la page-->
<div  class="main_content">
    <div  class="section pb_20">
        <div  class="container">
            <div  class="row">
                <!-- boucle collection-->
                {% for collection in collections %}
                <div  class="col-md-6">
                    <div  class="single_banner"><img alt="shop_banner_img1" src="{{ collection.image.url }}">
                        <div  class="single_banner_info">
                            <h5 class="single_bn_title1">{{ collection.description }}</h5>
                            <h3 class="single_bn_title">{{ collection.title }}</h3>
                            <a class="single_bn_link" href="{{ collection.button_link }}">{{ collection.button_text }}</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div  class="section small_pt pb_70">
        <div  class="container">
            <div  class="row justify-content-center">
                <div  class="col-md-6">
                    <div  class="heading_s1 text-center">
                        <h2 >Exclusive Products</h2>
                    </div>
                </div>
            </div>
            <div  class="row">
                <div  class="col-12">
                    <div  class="tab-style1">
                        <ul  role="tablist" class="nav nav-tabs justify-content-center">
                            <li  class="nav-item">
                                <a id="arrival-tab" data-bs-toggle="tab" href="#arrival" role="tab" aria-controls="arrival" aria-selected="true" class="nav-link active">New Arrival</a>
                            </li>
                            <li  class="nav-item">
                                <a id="sellers-tab" data-bs-toggle="tab" href="#sellers" role="tab" aria-controls="sellers" aria-selected="false" class="nav-link">Best Sellers</a>
                            </li>
                            <li  class="nav-item">
                                <a id="featured-tab" data-bs-toggle="tab" href="#featured" role="tab" aria-controls="featured" aria-selected="false" class="nav-link">Featured</a>
                            </li>
                            <li  class="nav-item">
                                <a id="special-tab" data-bs-toggle="tab" href="#special" role="tab" aria-controls="special" aria-selected="false" class="nav-link">Special Offer </a>
                            </li>
                        </ul>
                    </div>
                    <div  class="tab-content">
                        <div  id="arrival" role="tabpanel" aria-labelledby="arrival-tab"  class="tab-pane fade show active">
                            <div  class="row shop_container">

                                {% for product in new_arrivals %}
 
                                <div  class="col-lg-3 col-md-4 col-6">
                                    {% include "partials/product.html" with product=product %}

                                </div>
                                {% endfor %}

                            </div>
                        </div>
                        <div id="sellers" role="tabpanel" aria-labelledby="sellers-tab" class="tab-pane fade">
                            <div class="row shop_container">
                                {% for product in best_sellers %}
 
                                <div  class="col-lg-3 col-md-4 col-6">
                                    {% include "partials/product.html" with product=product %}

                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div id="featured" role="tabpannel" aria-labelledby="sellers-tab" class="tab-pane fade">
                            <div class="row shop_container">
                                {% for product in featured %}
 
                                <div  class="col-lg-3 col-md-4 col-6">
                                    {% include "partials/product.html" with product=product %}

                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div id="special" role="tabpanel" aria-labelledby="special-tab" class="tab-pane fade">
                            <div class="row shop_container">
                                {% for product in special_offers %}
 
                                <div  class="col-lg-3 col-md-4 col-6">
                                    {% include "partials/product.html" with product=product %}

                                </div>
                                {% endfor %}
                            </div>
                        </div>                                
                    </div>          
                </div>
            </div>
        </div>
    </div>
</div>                
{% endblock %}

mystore/templates/shop/page.html
{% extends "base.html" %}

{% block content %}

{% include "partials/top_page.html" with name=page.name %}

<div class="section pb_70">
    <div class="container">
        {{ page.content | safe}}
    </div>
</div>
{% endblock %}

mystore/templates/shop/wishlist.html
{% extends "base.html" %}
{% load price_filter %}

{% block content %}

{% include "partials/top_page.html" with name="Wish List" %}

<div  class="main_content">
    <div  class="section">
        <div  class="container">
            <div  class="row">
                <div  class="col-12">
                    <div  class="table-responsive wishlist_table">
                        <table  class="table">
                            <thead >
                                <tr >
                                    <th  class="product-thumbnail">&nbsp;</th>
                                    <th  class="product-name">Product</th>
                                    <th  class="product-price">Price</th>
                                    <th  class="product-stock-status">Stock Status</th>
                                    <th  class="product-add-to-cart"></th>
                                    <th  class="product-remove">Remove</th>
                                </tr>
                            </thead>
                            <tbody >
                                {% for product in wishlist %}
                                <tr >
                                    <td  class="product-thumbnail">
                                        <a href="{% url 'shop:single_product' product.slug %}">
                                            <img width="50" height="50" alt="product1" src="{{ product.image }}">
                                        </a>
                                    </td>
                                    <td data-title="Product" class="product-name">
                                        <a href="#">{{ product.name }}</a>
                                    </td>
                                    <td  data-title="Price" class="product-price">
                                        {{ product.solde_price | format_price }}
                                    </td>
                                    <td  data-title="Stock Status" class="product-stock-status">
                                        {% if product.stock > 0 %}
                                        <span class="in-stock">En Stock</span>
                                        {% else %}
                                        <span class="out-stock">Pas disponible</span>
                                        {% endif %}
                                    </td>
                                    <td  class="product-add-to-cart">
                                        <a href="{% url 'shop:add_to_cart' product.id %}" class="btn btn-fill-out">
                                            <i class="icon-basket-loaded"></i> Ajouter au panier
                                        </a>
                                    </td>
                                    <td  data-title="Remove" class="product-remove">
                                        <a href="{% url 'shop:remove_from_wishlist' product.id %}">
                                            <i class="ti-close"></i>
                                        </a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}