mystore/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('', include('shop.urls')),
]

#Ajout d'une configuration pour correctement afficher élément dans panneau admin lorsque le site est encore en mode DEBUG : 
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

mystore/shop/urls.py
from django.urls import path
from shop.views import shop_view , cart_view, compare_view, wishlist_view, checkout_view

app_name="shop" #nom de l'app

urlpatterns = [
    #Shop
    path('', shop_view.index, name='home'),
    path('page/<str:slug>', shop_view.display_page, name='page'),
    path('product/<str:slug>', shop_view.display_product, name='single_product'),
    path('shop', shop_view.shop, name='shop_list'),

    #Cart (panier)
    path('cart', cart_view.index, name='cart'),
    path('cart/add/<int:product_id>', cart_view.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/<int:quantity>', cart_view.remove_from_cart, name='remove_from_cart'),

    #Comparaison
    path('compare', compare_view.index, name='compare'),
    path('compare/add/<int:product_id>', compare_view.add_to_compare, name='add_to_compare'),
    path('compare/remove/<int:product_id>', compare_view.remove_from_compare, name='remove_from_compare'),

    #Liste des souhaits
    path('wishlist', wishlist_view.index, name='wishlist'),
    path('wishlist/add/<int:product_id>', wishlist_view.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:product_id>', wishlist_view.remove_from_wishlist, name='remove_from_wishlist'),

    #Checkout
    path('checkout', checkout_view.index, name='checkout'),
    path('checkout/add_address', checkout_view.add_address, name='add_address'),

]

mystore/shop/models/Product.py
from django.db import models
from shop.models.Category import Category
from django.utils.text import slugify


class Product(models.Model):
    name = models.CharField(max_length=60,blank=False, null=False)
    slug = models.SlugField(max_length=255,blank=False, null=False)
    description = models.CharField(max_length=120,blank=False, null=False)
    more_description = models.TextField(blank=True, null=True)
    additional_infos = models.TextField(blank=True, null=True)
    stock = models.IntegerField(blank=False, null=False)
    solde_price = models.FloatField(blank=False, null=False)
    regular_price = models.FloatField(blank=False, null=False)
    brand = models.CharField(max_length=60,blank=True, null=True)
    is_available = models.BooleanField(blank=False, null=False)
    is_best_seller = models.BooleanField(blank=False, null=False)
    is_new_arrival = models.BooleanField(blank=False, null=False)
    is_featured = models.BooleanField(blank=False, null=False)
    is_special_offer = models.BooleanField(blank=False, null=False)
    categories = models.ManyToManyField(Category)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs) : #création du champ slug lors de la création dans le panel admin
        if not self.slug :
            self.slug = slugify(self.name)
        super().save( *args, **kwargs)

mystore/shop/models/Slider.py
from django.db import models

class Slider(models.Model):
    title = models.CharField(max_length=60, blank=False, null=False)
    description = models.CharField(max_length=120,blank=False, null=False)
    button_text = models.CharField(max_length=60,blank=False, null=False)
    button_link = models.CharField(max_length=255,blank=False, null=False)
    image = models.ImageField(upload_to="sliders", blank=False, null=False)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

mystore/templates/partials/footer.html
{% load static %}

<footer  class="footer_dark">
    <div  class="footer_top">
        <div  class="container">
            <div  class="row">
                <div  class="col-lg-3 col-md-6 col-sm-12">
                    <div  class="widget">
                        <div  class="footer_logo"><a  href="#">
                                <h2>{{ request.session.name }}</h2>
                            </a></div>
                        <p >{{ request.session.description }} </p>
                    </div>
                    <div  class="widget">
                        <ul  class="social_icons social_white">
                            {% for social in request.session.socials %}
                            <li>
                                <a target="_blank" href="{{social.link}}"><i class="{{social.icon}}"></i></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-2 col-md-3 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">Useful Links</h6>
                        <ul  class="widget_links">
                            {% for page in request.session.foot_pages %}
                            <li>
                                <a  href="{% url 'shop:page' page.slug %}">{{ page.name }}</a>
                            </li>
                            {% endfor %}    
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-2 col-md-3 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">Category</h6>
                        <ul  class="widget_links">
                            <li ><a  href="#">Men</a></li><!-- A changer-->
                            <li ><a  href="#">Woman</a></li><!-- A changer-->
                            <li ><a  href="#">Kids</a></li><!-- A changer-->
                            <li ><a  href="#">Best Saller</a></li><!-- A changer-->
                            <li ><a  href="#">New Arrivals</a></li><!-- A changer-->
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-2 col-md-6 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">My Account</h6>
                        <ul  class="widget_links">
                            <li >
                                <a routerlink="account" ng-reflect-router-link="account" href="/account">Mon Compte</a>
                            </li>
                            <li >
                                <a routerlink="terms" ng-reflect-router-link="terms" href="/terms">Terms</a>
                            </li>
                            <li >
                                <a routerlink="signin" ng-reflect-router-link="signin" href="/signin">Se connecter</a>
                            </li>
                            <li ><a routerlink="signup" ng-reflect-router-link="signup" href="/signup">S'inscrire</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div  class="col-lg-3 col-md-4 col-sm-6">
                    <div  class="widget">
                        <h6  class="widget_title">Informations de Contact</h6>
                        <ul  class="contact_info contact_info_light">
                            <li >
                                <i class="ti-location-pin"></i>
                                <p>{{ request.session.street }}<br> {{ request.session.code_postal }} {{ request.session.city }} </p>
                            </li>
                            <li >
                                <i class="ti-email"></i>
                                <a href="mailto:{{ request.session.email }}">{{ request.session.email }}</a> <!-- A changer-->
                            </li>
                            <li >
                                <i  class="ti-mobile"></i>
                                <p >{{ request.session.phone }}</p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div  class="bottom_footer border-top-tran">
        <div  class="container">
            <div  class="row">
                <div  class="col-md-6">
                    <p  class="mb-md-0 text-center text-md-start"> {{ request.session.copyright }} </p>
                </div>
                <div  class="col-md-6">
                    <ul class="footer_payment text-center text-lg-end d-flex gap-2 justify-content-end">
                        <li >
                            <a href="#"><img src="{% static 'assets/images/visa.png' %}" alt="visa"></a>
                        </li>
                        <li >
                            <a href="#"><img src="{% static 'assets/images/discover.png' %}" alt="discover"></a>
                        </li>
                        <li >
                            <a href="#"><img src="{% static 'assets/images/master_card.png' %}" alt="master_card"></a>
                        </li>
                        <li >
                            <a href="#"><img src="{% static 'assets/images/paypal.png' %}" alt="paypal"></a>
                        </li>
                        <li >
                            <a  href="#"><img src="{% static 'assets/images/amarican_express.png' %}" alt="amarican_express"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

mystore/templates/partials/pagination.html
{% if datas.has_other_pages %}<!-- Vérification s'il y a bien plusieurs pages-->
<div class="row">
    <div class="col-12">
        <ul class="pagination mt-3 justify-content-center pagination_style1">
            {% if datas.has_previous %} <!--Vérifie s'il y a des pages précédentes -->
            <li class="page-item">
                <a class="page-link" href="?page={{ datas.previous_page_number }}">
                    <i class="linearicons-arrow-left"></i>
                </a>

            </li>
            <li class="page-item">
                <a class="page-link" href="?page=1">
                    1
                </a>
            </li>
            <li class="page-item">
                <a class="page-link" href="#">
                    ...
                </a>
            </li>
            {% endif %}

            {% for page in datas.paginator.page_range %} <!--Boucle pour afficher les pages dans le range de page qui existe via paginator -->
            {% if datas.number == page %} <!-- on vérifie s'il s'agit de la page courante afin d'ajouter active si c'est le cas-->
                <li class="page-item active">
                    <a class="page-link" href="?page={{page}}">{{ page }}</a>
                </li>
            {% elif page > datas.number|add:'-2' and page < datas.number|add:'+2' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page}}">{{ page }}</a>
                </li>
            {% endif %}
            {% endfor %}

            {% if datas.has_next %} <!--Vérifie s'il y a des pages suivantes -->
                <li class="page-item">
                    <a class="page-link" href="#">
                        ...
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ datas.paginator.num_pages }}">
                        {{ datas.paginator.num_pages }}
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ datas.next_page_number }}">
                        <i class="linearicons-arrow-right"></i>
                    </a>
                </li>
            {% endif %}

        </ul>
    </div>
</div>
{% endif %}

mystore/templates/partials/product.html
{% load price_filter %}
<div  class="product">
    <div  class="product_img">
        <a href="{% url 'shop:single_product' product.slug %}"><img alt="{{ product.name }}" src="{{ product.images.first.image.url }}"></a>
        <div  class="product_action_box">
            <ul  class="list_none pr_action_btn">
                <li  class="add-to-cart">
                    <a href="{% url 'shop:add_to_cart' product.id %}"><i class="icon-basket-loaded"></i> Ajouter au panier </a>
                </li>
                <li >
                    <a href="{% url 'shop:add_to_compare' product.id %}" ><i class="icon-shuffle"></i></a>
                </li>
                <li >
                    <a href="shop-quick-view.html" ><i class="icon-magnifier-add"></i></a>
                </li>
                <li >
                    <a href="{% url 'shop:add_to_wishlist' product.id %}"><i class="icon-heart"></i></a>
                </li>
            </ul>
        </div>
    </div>
    <div  class="product_info">
        <h6 class="product_title">
            <a href="{% url 'shop:single_product' product.slug %}"> {{ product.name }}</a>
        </h6> 
        <div  class="product_price">
            <span class="price">{{ product.solde_price | format_price }}</span><del>{{ product.regular_price | format_price }}</del><div  class="on_sale"><span>{{ product | solde_rate }}</span></div>
        </div>
        <div  class="rating_wrap">
            <div  class="rating">
                <div  class="product_rate" style="width: 80%;"></div>
            </div><span class="rating_num">(21)</span>
        </div>
        <div  class="pr_desc">
            <p >{{ product.description | safe }}</p>
        </div>
        <div  class="pr_switch_wrap">
            <div  class="product_color_switch"><span data-color="#87554B" class="active"></span><span data-color="#333333"></span><span data-color="#DA323F"></span>
            </div>
        </div>
    </div>
</div>

mystore/templates/partials/slider.html
<div  class="banner_section slide_medium shop_banner_slider staggered-animation-wrap">
    <div  id="carouselExampleControls" data-bs-ride="carousel" class="carousel slide carousel-fade light_arrow">
        <div  class="carousel-inner">
            <!--boucle de gestion des slides-->
            {% for slide in sliders %}
            <div  class="carousel-item background_bg  {% if forloop.first %}active{% endif %}" 
               
                data-img-src="{{ slide.image.url }}"
                style="background-image: url({{slide.image.url}});">
                <div  class="banner_slide_content">
                    <div  class="container">
                        <div  class="row">
                            <div  class="col-lg-7 col-9">
                                <div  class="banner_content overflow-hidden">
                                    <h5  data-animation="slideInLeft"
                                        data-animation-delay="0.5s"
                                        class="mb-3 staggered-animation font-weight-light animated slideInLeft"
                                        style="animation-delay: 0.5s; opacity: 1;">{{ slide.description }}</h5>
                                    <h2  data-animation="slideInLeft"
                                        data-animation-delay="1s" class="staggered-animation animated slideInLeft"
                                        style="animation-delay: 1s; opacity: 1;">{{ slide.title }}</h2><a
                                         data-animation="slideInLeft"
                                        data-animation-delay="1.5s"
                                        class="btn btn-fill-out rounded-0 staggered-animation text-uppercase animated slideInLeft"
                                        href="{{ slide.button_link }}"
                                        style="animation-delay: 1.5s; opacity: 1;">{{ slide.button_text }}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                
            {% endfor %}

        </div>
        <a  href="#carouselExampleControls" role="button" data-bs-slide="prev" class="carousel-control-prev"><i  class="ion-chevron-left"></i></a>
        <a  href="#carouselExampleControls" role="button" data-bs-slide="next" class="carousel-control-next"><i  class="ion-chevron-right"></i></a>
    </div>
</div>

mystore/templates/partials/top_page.html
<div class="breadcrumb_section bg_gray page-title-mini">
    <div class="container"><!-- STRART CONTAINER -->
        <div class="row align-items-center">
        	<div class="col-md-6">
                <div class="page-title">
            		<h1>{{name}}</h1>
                </div>
            </div>
            <div class="col-md-6">
                <ol class="breadcrumb justify-content-md-end">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">Pages</a></li>
                    <li class="breadcrumb-item active">{{name}}</li>
                </ol>
            </div>
        </div>
    </div><!-- END CONTAINER-->
</div>